# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eafd58fb6405a55fc0a72571589921e3f7a7b074a7f7a3ba23fca0184d1d38f138d0f1a33773b4a47e9de3b2a681a424577d37b1d96afcbfa8b6e1dd53d43c2e

test:
  secret_key_base: 3c1f48fb8c3448cfb01dfd4f1a323a75ad4d72c9a71ce7dd9c487a09900b2ad7df53bb890eb465fc9246a971d868dcde314d6844fb06c838a448a22703684746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
